apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hugging-face-token-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: huggingface.co
    creationPolicy: Owner
  data:
    - secretKey: HUGGING_FACE_HUB_TOKEN
      remoteRef:
        key: HUGGING_FACE_HUB_TOKEN
