external-secrets:
  serviceAccount:
    create: false
    name: external-secrets
    # annotations:
    #   eks.amazonaws.com/role-arn: arn:aws:iam::270387482367:role/eu-north-1-dev-eks-external-secrets