apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  amiFamily: AL2
  amiSelectorTerms:
    - alias: al2
  role: "eu-north-1-dev-eks-nodes"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eu-north-1-dev-eks"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eu-north-1-dev-eks"
